//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vol_org.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doh_num
    {
        public int ID { get; set; }
        public int dohidna_ID { get; set; }
        public string number { get; set; }
        public int quantity { get; set; }
        public int mc_ID { get; set; }
    
        public virtual MC MC { get; set; }
        public virtual Dohidna_n Dohidna_n { get; set; }
        public virtual MC MC1 { get; set; }
    }
}
