//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vol_org.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dohidna_n
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dohidna_n()
        {
            this.Doh_num = new HashSet<Doh_num>();
        }
    
        public int ID { get; set; }
        public System.DateTime date { get; set; }
        public int member_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doh_num> Doh_num { get; set; }
        public virtual Member Member { get; set; }
        public virtual Vydatkovy_ko Vydatkovy_ko { get; set; }
    }
}
