//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vol_org.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class volunteer_orgEntities : DbContext
    {
        public volunteer_orgEntities()
            : base("name=volunteer_orgEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Balance> Balance { get; set; }
        public virtual DbSet<Doh_num> Doh_num { get; set; }
        public virtual DbSet<Dohidna_n> Dohidna_n { get; set; }
        public virtual DbSet<MC> MC { get; set; }
        public virtual DbSet<MC_remain> MC_remain { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<Prybutkovy_ko> Prybutkovy_ko { get; set; }
        public virtual DbSet<Reciever> Reciever { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Vydatkova_n> Vydatkova_n { get; set; }
        public virtual DbSet<Vydatkovy_ko> Vydatkovy_ko { get; set; }
    }
}
